---
title: "analysis"
author: "Patrick"
date: "2023-07-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(RSocrata)

library(rvest)
library(xml2)
```

```{r}

marshall_revenue <- read.socrata("https://data.cityofnewyork.us/resource/7ewi-9cdf.csv") %>% 
  separate(marshal_last_name, into = c("marshal_last_name", "marshal_first init"), sep = ", | \\(")

```

```{r}
# URL of the website containing the table
url <- "https://www.nyc.gov/site/doi/offices/marshals-list.page"

# Read the HTML content of the page
page <- read_html(url)

# Extract the table from the HTML content
# Replace "table_selector" with the CSS selector of the table you want to scrape
# You can find the selector using browser developer tools (right-click on the table and inspect)
table_selector <- "table"

# Extract the table and store it in a data frame
marshalls_list <- page %>%
  html_table(fill = TRUE) %>% 
  .[[1]]

```

```{r}
evictions <- read.socrata("https://data.cityofnewyork.us/resource/6z8x-wfk4.csv") %>% 
  mutate(year = year(executed_date))

executed_by_marshall_year <- evictions %>% 
  group_by(marshal_first_name, marshal_last_name, year) %>% 
  summarize(no_evictions = sum(!is.na(executed_date), na.rm = T))


  

```

```{r}
marshalls_evictions_revenue <- full_join(marshall_revenue, executed_by_marshall_year, by = c("marshal_last_name" = "marshal_last_name", "year" = "year"))

last_year <- marshalls_evictions_revenue %>% 
  filter(year == 2023)
```

```{r}

income_year_total <- marshall_revenue %>% 
  group_by(year) %>% 
  summarize(total_income = sum(net_income_marshal_s_office, na.rm = T))

write_csv(income_year_total %>% filter(year > 2016), "income_year.csv")


evictions_year_total <- evictions %>% 
  group_by(year) %>% 
  summarize(total_evictions = n())

write_csv(evictions_year_total %>% filter(year < 2024), "evictions_year.csv")

left_join(evictions_year_total %>% filter(year < 2024), income_year_total %>% filter(year > 2016)) %>% 
  write_csv("evictions_income_year.csv")

```

