---
title: "donations"
author: "Patrick"
date: "2024-06-06"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

```{r}

marshals_assoc_contributions <- read_csv("https://data.ny.gov/resource/e9ss-239a.csv?$query=SELECT%0A%20%20%60filer_id%60%2C%0A%20%20%60filer_previous_id%60%2C%0A%20%20%60cand_comm_name%60%2C%0A%20%20%60election_year%60%2C%0A%20%20%60election_type%60%2C%0A%20%20%60county_desc%60%2C%0A%20%20%60filing_abbrev%60%2C%0A%20%20%60filing_desc%60%2C%0A%20%20%60r_amend%60%2C%0A%20%20%60filing_cat_desc%60%2C%0A%20%20%60filing_sched_abbrev%60%2C%0A%20%20%60filing_sched_desc%60%2C%0A%20%20%60loan_lib_number%60%2C%0A%20%20%60trans_number%60%2C%0A%20%20%60trans_mapping%60%2C%0A%20%20%60sched_date%60%2C%0A%20%20%60org_date%60%2C%0A%20%20%60cntrbr_type_desc%60%2C%0A%20%20%60cntrbn_type_desc%60%2C%0A%20%20%60transfer_type_desc%60%2C%0A%20%20%60receipt_type_desc%60%2C%0A%20%20%60receipt_code_desc%60%2C%0A%20%20%60purpose_code_desc%60%2C%0A%20%20%60r_subcontractor%60%2C%0A%20%20%60flng_ent_name%60%2C%0A%20%20%60flng_ent_first_name%60%2C%0A%20%20%60flng_ent_middle_name%60%2C%0A%20%20%60flng_ent_last_name%60%2C%0A%20%20%60flng_ent_add1%60%2C%0A%20%20%60flng_ent_city%60%2C%0A%20%20%60flng_ent_state%60%2C%0A%20%20%60flng_ent_zip%60%2C%0A%20%20%60flng_ent_country%60%2C%0A%20%20%60payment_type_desc%60%2C%0A%20%20%60pay_number%60%2C%0A%20%20%60owed_amt%60%2C%0A%20%20%60org_amt%60%2C%0A%20%20%60loan_other_desc%60%2C%0A%20%20%60trans_explntn%60%2C%0A%20%20%60r_itemized%60%2C%0A%20%20%60r_liability%60%2C%0A%20%20%60election_year_r%60%2C%0A%20%20%60office_desc%60%2C%0A%20%20%60district%60%2C%0A%20%20%60dist_off_cand_bal_prop%60%0AWHERE%20caseless_contains(%60flng_ent_add1%60%2C%20%22120%20Westchester%20Sq%22)%0AORDER%20BY%20%60election_year%60%20DESC%20NULL%20LAST")

```




```{r}
filers <- read_csv("filers_6.6.24.csv", )

names(filers) <- c("filer_id", "filer_name", "compliance_type_desc", "filter_type_desc", "filer_status", "committee_type_desc",
                                    "office_desc", "district", "county_desc", "municipality_desc_subdivision_desc", "treasurer_first_name",  "treasurer_middle_name", "treasurer_last_name", "address", "city", "state", "zipcode")
```

```{r}

state_candidates <- read_csv("STATE_CANDIDATE.csv")

var_names <- c(
'FILER_ID',
'FILER_PREVIOUS_ID',
'CAND_COMM_NAME',
'ELECTION_YEAR',
'ELECTION_TYPE',
'COUNTY_DESC',
'FILING_ABBREV',
'FILING_DESC',
'R_AMEND',
'FILING_CAT_DESC',
'FILING_SCHED_ABBREV',
'FILING_SCHED_DESC',
'LOAN_LIB_NUMBER',
'TRANS_NUMBER',
'TRANS_MAPPING',
'SCHED_DATE',
'ORG_DATE',
'CNTRBR_TYPE_DESC',
'CNTRBN_TYPE_DESC',
'TRANSFER_TYPE_DESC',
'RECEIPT_TYPE_DESC',
'RECEIPT_CODE_DESC',
'PURPOSE_CODE_DESC',
'R_SUBCONTRACTOR',
'FLNG_ENT_NAME',
'FLNG_ENT_FIRST_NAME',
'FLNG_ENT_MIDDLE_NAME',
'FLNG_ENT_LAST_NAME',
'FLNG_ENT_ADD1',
'FLNG_ENT_CITY',
'FLNG_ENT_STATE',
'FLNG_ENT_ZIP',
'FLNG_ENT_COUNTRY',
'PAYMENT_TYPE_DESC',
'PAY_NUMBER',
'OWED_AMT',
'ORG_AMT',
'LOAN_OTHER_DESC',
'TRANS_EXPLNTN',
'R_ITEMIZED',
'R_LIABILITY',
'ELECTION_YEAR_R',
'OFFICE_DESC',
'DISTRICT',
'DIST_OFF_CAND_BAL_PROP'
                             )

names(state_candidates) <- var_names
state_committees <- read_csv("STATE_COMMITTEE.csv")
names(state_committees) <- var_names


```


